### ISSUE TITLE
Problem when changing user language

### ISSUE THREAD

**Issue by RCatersels** [mendix/SimpleCharts#10]
See also forum post here: [https://mxforum.mendix.com/questions/17822/Login-problem-when-changing-user-language]
The root cause was the simple chart widget. Removing it solved the issue.
We removed this widget if favour of the ChartJS widget. Would be interested in the view of Mendix which chart widget will be supported by Mendix though. 

Regards,

Ronald

**Comment by JelteMX** [comment]
That is pretty simple: We do not support SImpleCharts anymore. This is explicitly stated on [Github](https://github.com/mendix/SimpleCharts/blob/master/README.md), but I noticed there was a warning missing in the AppStore. 

So I added this to the AppStore as well, to make people aware that we do not actively support SimpleCharts and the behaviour of this widget can be flaky
