### ISSUE TITLE
Upgrade simplecharts to new Boilerplate (AMD) structure

### ISSUE THREAD

**Issue by rvanosnabrugge** [mendix/SimpleCharts#8]
Dear,

The Simplechart widget is not compatible with Mendix 6, probably because of deprecated libraries or the new AMD structure.

- Does anyone else experiences the same problem?
- Does anybody has an idea how to fix this?

Could use some help here :) Thank you in advance!

Kind regards,
Richard

**Comment by JelteMX** [comment]
I pulled in #3 to the [mx6-branch](https://github.com/mendix/SimpleCharts/tree/mx6), which contains an AMD structure. Let's work on that branch to update it to an MX6 compatible widget.
